##
# Add your Google Analytics, User Voice, New Relic params.
##
defaults: &defaults
  ganalytics: YOUR_ANALYTICS
  uservoice: YOUR_USERVOICE.js
  newrelic: YOUR_NEW_RELIC

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
