##
# Add your Google Analytics, User Voice, New Relic params.
##

defaults: &defaults
  ganalytics: YOUR_ANALYTICS
  uservoice: YOUR_USER_VOICE.js
  newrelic: YOUR_NEWRELIC

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
