require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassResourcesController do

  # This should return the minimal set of attributes required to create a valid
  # ClassResource. As you add validations to ClassResource, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all class_resources as @class_resources" do
      class_resource = ClassResource.create! valid_attributes
      get :index
      assigns(:class_resources).should eq([class_resource])
    end
  end

  describe "GET show" do
    it "assigns the requested class_resource as @class_resource" do
      class_resource = ClassResource.create! valid_attributes
      get :show, :id => class_resource.id.to_s
      assigns(:class_resource).should eq(class_resource)
    end
  end

  describe "GET new" do
    it "assigns a new class_resource as @class_resource" do
      get :new
      assigns(:class_resource).should be_a_new(ClassResource)
    end
  end

  describe "GET edit" do
    it "assigns the requested class_resource as @class_resource" do
      class_resource = ClassResource.create! valid_attributes
      get :edit, :id => class_resource.id.to_s
      assigns(:class_resource).should eq(class_resource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassResource" do
        expect {
          post :create, :class_resource => valid_attributes
        }.to change(ClassResource, :count).by(1)
      end

      it "assigns a newly created class_resource as @class_resource" do
        post :create, :class_resource => valid_attributes
        assigns(:class_resource).should be_a(ClassResource)
        assigns(:class_resource).should be_persisted
      end

      it "redirects to the created class_resource" do
        post :create, :class_resource => valid_attributes
        response.should redirect_to(ClassResource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved class_resource as @class_resource" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassResource.any_instance.stub(:save).and_return(false)
        post :create, :class_resource => {}
        assigns(:class_resource).should be_a_new(ClassResource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassResource.any_instance.stub(:save).and_return(false)
        post :create, :class_resource => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested class_resource" do
        class_resource = ClassResource.create! valid_attributes
        # Assuming there are no other class_resources in the database, this
        # specifies that the ClassResource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassResource.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => class_resource.id, :class_resource => {'these' => 'params'}
      end

      it "assigns the requested class_resource as @class_resource" do
        class_resource = ClassResource.create! valid_attributes
        put :update, :id => class_resource.id, :class_resource => valid_attributes
        assigns(:class_resource).should eq(class_resource)
      end

      it "redirects to the class_resource" do
        class_resource = ClassResource.create! valid_attributes
        put :update, :id => class_resource.id, :class_resource => valid_attributes
        response.should redirect_to(class_resource)
      end
    end

    describe "with invalid params" do
      it "assigns the class_resource as @class_resource" do
        class_resource = ClassResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassResource.any_instance.stub(:save).and_return(false)
        put :update, :id => class_resource.id.to_s, :class_resource => {}
        assigns(:class_resource).should eq(class_resource)
      end

      it "re-renders the 'edit' template" do
        class_resource = ClassResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassResource.any_instance.stub(:save).and_return(false)
        put :update, :id => class_resource.id.to_s, :class_resource => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested class_resource" do
      class_resource = ClassResource.create! valid_attributes
      expect {
        delete :destroy, :id => class_resource.id.to_s
      }.to change(ClassResource, :count).by(-1)
    end

    it "redirects to the class_resources list" do
      class_resource = ClassResource.create! valid_attributes
      delete :destroy, :id => class_resource.id.to_s
      response.should redirect_to(class_resources_url)
    end
  end

end
